# -*- mode: python -*-

Import("env")

env.Library(
    target= 'storage_berkeley1',
    source= [
        'berkeley1_engine.cpp',
        'berkeley1_recovery_unit.cpp',
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson'
        ]
    )
