# -*- mode: python -*-

Import("env")

env.Library(
    target= 'storage_berkeley1',
    source= [
        'berkeley1_engine.cpp',
        'berkeley1_recovery_unit.cpp',
        'berkeley1_database_catalog_entry.cpp',
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson',
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        '$BUILD_DIR/mongo/db/structure/record_store',
        '$BUILD_DIR/mongo/foundation',
        '$BUILD_DIR/mongo/db/structure/record_store_berkeley',
        ]
    )
