# -*- mode: python -*-

Import("env")

env.Library(
    target= 'berkeley_storage_engine',
    source= [
        'berkeley_recovery_unit.cpp',
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson'
        ]
    )
