Import("env")
Import("has_option")

if has_option("twitter"):

    env.Library(
        target= 'storage_twitter_base',
        source= [
            'twitter_btree_impl.cpp',
            'twitter_collection_catalog_entry.cpp',
            'twitter_database_catalog_entry.cpp',
            'twitter_engine.cpp',
            'twitter_cud.cpp',
            'twitter_record_store.cpp',
            ],
        LIBDEPS= [
            '$BUILD_DIR/mongo/bson',
            '$BUILD_DIR/mongo/db/catalog/collection_options',
            '$BUILD_DIR/mongo/db/structure/record_store',
            '$BUILD_DIR/mongo/foundation',
            '$BUILD_DIR/third_party/shim_snappy',
            ],
        )

    env.Library(
        target= 'storage_twitter',
        source= [
            'twitter_init.cpp'
            ],
        LIBDEPS= [
            'storage_twitter_base'
            ]
        )

