
Import("env")

env.Library(
    target= 'record_store',
    source= [
        'record_store.cpp',
        'record_store_heap.cpp'
        ],
    LIBDEPS= [
        '$BUILD_DIR/mongo/bson',
        '$BUILD_DIR/mongo/db/commands/server_status_core',
        '$BUILD_DIR/mongo/db/storage/extent',
        '$BUILD_DIR/mongo/db/storage/berkeley/berkeley_storage_engine',
        '$BUILD_DIR/mongo/foundation',
        '$BUILD_DIR/mongo/mongocommon',
        ]
    )

env.Library(
    target= 'record_store_v1',
    source= [
        'record_store_v1_base.cpp',
        'record_store_v1_capped.cpp',
        'record_store_v1_capped_iterator.cpp',
        'record_store_v1_repair_iterator.cpp',
        'record_store_v1_simple.cpp',
        'record_store_v1_simple_iterator.cpp',
        ],
    LIBDEPS= [
        'record_store',
        ]
    )

env.Library(
    target='record_store_v1_test_help',
    source=['record_store_v1_test_help.cpp',
            ],
    LIBDEPS=[
        'record_store_v1'
        ]
    )

env.Library(
    target='record_store_berkeley',
    source=['record_store_berkeley.cpp',
            ],
    LIBDEPS=[
        'record_store'
        ]
    )

env.CppUnitTest(
    target='record_store_v1_simple_test',
    source=['record_store_v1_simple_test.cpp',
            ],
    LIBDEPS=[
        'record_store_v1_test_help'
        ]
    )

env.CppUnitTest(
    target='record_store_v1_capped_test',
    source=['record_store_v1_capped_test.cpp',
            ],
    LIBDEPS=[
        'record_store_v1_test_help'
        ]
    )

env.CppUnitTest(
    target='record_store_berkeley_test',
    source=['record_store_berkeley_test.cpp',
            ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/storage/berkeley/berkeley_storage_engine',
        '$BUILD_DIR/mongo/db/berkeley_operation_context',
        'record_store_berkeley'
        ]
    )
